:api_key: 868faa3836896e02d5abe139ab8f7d64
:password: 547897df44fc70ec1344b11cca247fe4
:theme_id: "33"
:preview_url: https://lojadetestes-tray-default.commercesuite.com.br/loja/loja.php?loja=1072894&opencode_theme=6214d143af20a
:debug: false
